[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.9
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true
